/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    // Button classes
    "btn",
    "btn-primary",
    "btn-secondary",
    "btn-outline",
    "text-sm",
    "text-base",
    "text-lg",
    
    // Card classes
    "card",
    "card-bordered",
    "card-shadowed",
    "card-hoverable",
    "card-header",
    "card-header-image",
    "card-header-overlay",
    "card-header-content",
    "card-body",
    "card-body-unpadded",
    "card-footer",
    "card-footer-bordered",
    
    // Input classes
    "input-wrapper",
    "input-label",
    "input-container",
    "input-field",
    "input-normal",
    "input-error",
    "input-disabled",
    "input-icon",
    "input-icon-left",
    "input-icon-right",
    "input-icon-left-position",
    "input-icon-right-position",
    "input-icon-size",
    "input-password-toggle",
    "input-password-toggle-button",
    "input-spinner",
    "input-helper-text",
    "input-helper-text-normal",
    "input-helper-text-error",
    
    // Avatar classes
    "avatar",
    "avatar-xs",
    "avatar-sm",
    "avatar-md",
    "avatar-lg",
    "avatar-xl",
    "avatar-square",
    "avatar-circle",
    "avatar-group",
    "avatar-status",
    "avatar-bordered",
    "avatar-img",
    "avatar-initials",
    "avatar-status-online",
    "avatar-status-offline",
    "avatar-status-busy",
    "avatar-status-away",
    
    // Modal classes
    "modal-overlay",
    "modal-content",
    "modal-header",
    "modal-body",
    "modal-footer",
    "modal-title",
    "modal-close-button",
    
    // Toast classes
    "toast",
    "toast-success",
    "toast-error",
    "toast-warning",
    "toast-info",
    "toast-progress",
    "toast-header",
    "toast-body",
    "toast-close-button",
    
    // Dropdown classes
    "dropdown-content",
    "dropdown-item",
    "dropdown-item-disabled",
    "dropdown-header",
    "dropdown-divider",
    
    // Common utility classes
    "animate-spin",
    "bg-opacity-40",
    "opacity-25",
    "opacity-75",
    "first:ml-0",
    "-ml-3",
    "ring-1",
    "ring-2",
    "ring-offset-2",
    "ring-white",
    "ring-black",
    "ring-opacity-5",
    
    // Background colors
    "bg-blue-500",
    "bg-blue-600",
    "bg-blue-700",
    "bg-red-500",
    "bg-red-50",
    "bg-green-500",
    "bg-green-50",
    "bg-yellow-500",
    "bg-yellow-50",
    "bg-gray-50",
    "bg-gray-100",
    "bg-gray-200",
    "bg-purple-500",
    "bg-pink-500",
    "bg-indigo-500",
    "bg-white",
    "bg-black",
    
    // Text colors
    "text-white",
    "text-gray-400",
    "text-gray-500",
    "text-gray-700",
    "text-gray-900",
    "text-red-500",
    "text-red-900",
    
    // Border colors
    "border-gray-200",
    "border-gray-300",
    "border-red-500",
    "border-green-500",
    "border-yellow-500",
    "border-blue-500",
    
    // Hover states
    "hover:bg-blue-700",
    "hover:bg-gray-50",
    "hover:bg-gray-100",
    "hover:bg-gray-200",
    "hover:text-gray-500",
    
    // Focus states
    "focus:ring-blue-500",
    "focus:ring-gray-500",
    "focus:ring-red-500",
    "focus:border-blue-500",
    "focus:border-red-500",
    "focus:outline-none"
  ],
  theme: {
    extend: {
      colors: {
        blue: {
          500: "#3b82f6",
          600: "#2563eb",
          700: "#1d4ed8",
        },
        gray: {
          50: "#f9fafb",
          100: "#f3f4f6",
          200: "#e5e7eb",
          300: "#d1d5db",
          400: "#9ca3af",
          500: "#6b7280",
          600: "#4b5563",
          700: "#374151",
          800: "#1f2937",
          900: "#111827",
        },
        green: {
          50: "#f0fdf4",
          500: "#22c55e",
          600: "#16a34a",
        },
        red: {
          50: "#fef2f2",
          500: "#ef4444",
          600: "#dc2626",
        },
        yellow: {
          50: "#fefce8",
          500: "#eab308",
          600: "#ca8a04",
        },
        purple: {
          500: "#a855f7",
        },
        pink: {
          500: "#ec4899",
        },
        indigo: {
          500: "#6366f1",
        },
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
        },
      },
    },
  },
  plugins: [],
};
